import { Montserrat  } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/index.js";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <div className="flex">
          <Sidebar />
          <div className="page">{children}</div>
        </div>
      </body>
    </html>
  );
}
