
import { Montserrat } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Navbar from "@/components/navbar";
import Bottombar from "@/components/bottombar";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children, showSidebar }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {showSidebar && <Navbar />}
        <div className={showSidebar ? "flex" : ""}>
          {showSidebar && <Sidebar />}
          <div className="page">{children}</div>
        </div>
        {showSidebar && <Bottombar />}
      </body>
    </html>)
}
